// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-BGRck0HJohn3NMh2MW8Najg34R5kok',
    appId: '1:799848895975:web:bb93b315f41038ee17d942',
    messagingSenderId: '799848895975',
    projectId: 'greenwich-app-13d83',
    authDomain: 'greenwich-app-13d83.firebaseapp.com',
    storageBucket: 'greenwich-app-13d83.appspot.com',
    measurementId: 'G-PDS4YF5EH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtUZ7tCAVFFeZVN-g2WzXfvsRat4A7bU',
    appId: '1:799848895975:android:5c44d66a64c0f58517d942',
    messagingSenderId: '799848895975',
    projectId: 'greenwich-app-13d83',
    storageBucket: 'greenwich-app-13d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsQhrbmHsPmwUPcSmvCC-P4VrtOetd36U',
    appId: '1:799848895975:ios:8564876d05c4c00317d942',
    messagingSenderId: '799848895975',
    projectId: 'greenwich-app-13d83',
    storageBucket: 'greenwich-app-13d83.appspot.com',
    iosBundleId: 'com.example.uog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsQhrbmHsPmwUPcSmvCC-P4VrtOetd36U',
    appId: '1:799848895975:ios:8564876d05c4c00317d942',
    messagingSenderId: '799848895975',
    projectId: 'greenwich-app-13d83',
    storageBucket: 'greenwich-app-13d83.appspot.com',
    iosBundleId: 'com.example.uog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF-BGRck0HJohn3NMh2MW8Najg34R5kok',
    appId: '1:799848895975:web:1fec9c12a82ed20617d942',
    messagingSenderId: '799848895975',
    projectId: 'greenwich-app-13d83',
    authDomain: 'greenwich-app-13d83.firebaseapp.com',
    storageBucket: 'greenwich-app-13d83.appspot.com',
    measurementId: 'G-5RL0X7Y6SH',
  );
}
